[tool.poetry]
name = "Ml Playground"
version = "0.1.0"
description = ""
authors = ["NickiHell <nickihell@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
gym = "*"
torch = "*"
torchvision = "*"
matplotlib = "*"
numpy = "*"
loguru = "*"
pyglet = "*"
pandas = "^1.3.4"
urllib3 = "^1.26.7"
device = "^0.1"

[tool.poetry.dev-dependencies]
ipython = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
